import fs from 'node:fs';
import path from 'node:path';

const root = process.cwd();
const csvDir = path.join(root, 'data', 'csv');
const outFile = path.join(root, 'src', 'data', 'generatedData.js');

function parseCsv(fileName) {
  const text = fs.readFileSync(path.join(csvDir, fileName), 'utf8').trim();
  const lines = text.split(/\r?\n/);
  const headers = lines[0].split(',');
  return lines.slice(1).filter(Boolean).map((line) => {
    const cols = line.split(',');
    return Object.fromEntries(headers.map((h, i) => [h, cols[i] ?? '']));
  });
}

const core = parseCsv('servants_core.csv');
const effects = parseCsv('servant_combat_effects.csv');
const tags = parseCsv('servant_check_tags.csv');
const intelRules = parseCsv('enemy_intel_rules.csv');
const classAffinityRows = parseCsv('class_affinity.csv');

const FSN_SERVANTS = core.map((r) => ({
  trueName: r.trueName,
  className: r.className,
  altClasses: r.altClasses ? r.altClasses.split('|').filter(Boolean) : [],
  stats: {
    筋力: Number(r.str),
    耐久: Number(r.end),
    敏捷: Number(r.agi),
    魔力: Number(r.mgc),
    幸運: Number(r.luk),
    宝具: Number(r.np),
  },
}));

const SERVANT_COMBAT_EFFECTS = {};
for (const row of effects) {
  if (!SERVANT_COMBAT_EFFECTS[row.trueName]) SERVANT_COMBAT_EFFECTS[row.trueName] = {};
  if (row.mode === 'passive') {
    SERVANT_COMBAT_EFFECTS[row.trueName].passiveLabel = row.label;
  } else {
    SERVANT_COMBAT_EFFECTS[row.trueName].npLabel = row.label;
  }
  SERVANT_COMBAT_EFFECTS[row.trueName][row.mode] = {
    bonus: Number(row.bonus),
    damage: Number(row.damage),
    manaCost: Number(row.manaCost),
    enemyPower: Number(row.enemyPower),
    backlashMaster: Number(row.backlashMaster),
    retreatBonus: Number(row.retreatBonus),
    exposureDelta: Number(row.exposureDelta),
    ...(Number(row.lowHpBonus) ? { lowHpBonus: Number(row.lowHpBonus) } : {}),
  };
}

const SERVANT_CHECK_TAG_SKILLS = {};
for (const row of tags) {
  if (!SERVANT_CHECK_TAG_SKILLS[row.trueName]) SERVANT_CHECK_TAG_SKILLS[row.trueName] = [];
  SERVANT_CHECK_TAG_SKILLS[row.trueName].push({
    name: row.skillName,
    checkTags: row.checkTags.split('|').filter(Boolean),
    passiveModifiers: {
      bonus: Number(row.bonus),
      damage: Number(row.damage),
      manaCost: Number(row.manaCost),
      enemyPower: Number(row.enemyPower),
      backlashMaster: Number(row.backlashMaster),
      retreatBonus: Number(row.retreatBonus),
      exposureDelta: Number(row.exposureDelta),
    },
  });
}


const CLASS_AFFINITY_TABLE = {};
for (const row of classAffinityRows) {
  if (!CLASS_AFFINITY_TABLE[row.attackerClass]) CLASS_AFFINITY_TABLE[row.attackerClass] = {};
  CLASS_AFFINITY_TABLE[row.attackerClass][row.defenderClass] = {
    multiplier: Number(row.multiplier),
    relation: row.relation,
  };
}

const ENEMY_INTEL_RULES = intelRules.map((r) => ({
  level: Number(r.level),
  revealStatsCount: Number(r.revealStatsCount),
  revealSkillCount: Number(r.revealSkillCount),
  revealTrueName: Number(r.revealTrueName),
  revealNpType: Number(r.revealNpType),
  revealNpName: Number(r.revealNpName),
}));

const output = `// AUTO-GENERATED by scripts/generate_csv_data.mjs\n// Source of truth: data/csv/*.csv\n\nexport const FSN_SERVANTS = ${JSON.stringify(FSN_SERVANTS, null, 2)};\n\nexport const SERVANT_COMBAT_EFFECTS = ${JSON.stringify(SERVANT_COMBAT_EFFECTS, null, 2)};\n\nexport const SERVANT_CHECK_TAG_SKILLS = ${JSON.stringify(SERVANT_CHECK_TAG_SKILLS, null, 2)};\n\nexport const ENEMY_INTEL_RULES = ${JSON.stringify(ENEMY_INTEL_RULES, null, 2)};\n\nexport const CLASS_AFFINITY_TABLE = ${JSON.stringify(CLASS_AFFINITY_TABLE, null, 2)};\n`;

fs.writeFileSync(outFile, output, 'utf8');
console.log(`generated: ${path.relative(root, outFile)}`);
